version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip curl
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Setting up Terraform Cloud credentials"
      - export TF_TOKEN_app_terraform_io=$TF_CLOUD_TOKEN
      - echo "Downloading full terraform code from S3"
      - aws s3 cp s3://$S3_BUCKET/$S3_KEY full_stack.tf
      - terraform init
      - terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

  build:
    commands:
      - terraform apply -auto-approve