version: 0.2

env:
  variables:
    TF_VAR_auto_approve: "true"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - apt-get update && apt-get install -y unzip curl
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - ls -al
      - cat terraform_app_layer.tf 
      - terraform init

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
